#!/usr/bin/env bun
/**
 * `infra:prepare` — start the minimal set of local services for a given
 * `(kernel, domain)` env pair. Idempotent. Mirrors distribution's script,
 * stripped of DO/Blaxel-specific bits.
 *
 *   bun run scripts/infra-prepare.ts --kernel <kernelPreset> --domain <domainPreset>
 *
 * See distribution/scripts/infra-prepare.ts for the full decision table
 * and DNS-preflight comments.
 */
import { domainUrl } from '@astrale-os/kernel-test'
import { kernelEnvs, type KernelEnvName } from '@astrale-os/kernel-toolkit'
import { spawnSync } from 'node:child_process'
import { lookup } from 'node:dns/promises'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { domainEnvs, readDomainPort, type DomainEnvName } from '../envs.ts'
import {
  DEFAULT_DEV_LOG_DIR,
  DEFAULT_TUNNEL_NAME,
  assertRuntimeSecrets,
  evalPreset,
  isAstraleRunning,
  isHttpOk,
  killWranglerTree,
} from './lib.ts'

const here = dirname(fileURLToPath(import.meta.url))
const domainRoot = join(here, '..')

const args = parseArgs(process.argv.slice(2))
if (!args.kernel || !args.domain) usage()
const kernelName = args.kernel as KernelEnvName
const domainName = args.domain as DomainEnvName

const kernel = evalPreset(kernelEnvs, kernelName, 'kernel')
const domain = evalPreset(domainEnvs, domainName, 'domain')

const needsAstrale = kernel.mode === 'manager' && !kernelName.startsWith('remote:')
const needsCloudflared = kernelName.endsWith(':tunneled') || domainName === 'local:tunneled'
const needsLocalWorker = domainName === 'local:inprocess' || domainName === 'local:tunneled'

const workerUrl = domainUrl(domain)
const workerIsTunneled = !/^https?:\/\/([^/]+\.)?localhost(:|\/|$)|^https?:\/\/127\./.test(
  workerUrl,
)

console.log(`Infra plan for ${kernelName} × ${domainName}`)
console.log(`  kernel:      ${JSON.stringify(kernel)}`)
console.log(`  domain:      ${JSON.stringify(domain)}`)
console.log(`  astrale:     ${needsAstrale}`)
console.log(`  cloudflared: ${needsCloudflared}`)
console.log(`  wrangler:    ${needsLocalWorker}`)

await preflightDns(kernelName, domainName)

if (needsAstrale) ensureAstrale()
if (needsCloudflared) ensureCloudflared()
if (needsLocalWorker) await ensureLocalWorker()

console.log('✓ infra ready')

function ensureAstrale(): void {
  console.log('==> astrale manager')
  if (isAstraleRunning()) {
    console.log('    already running')
    return
  }
  const s = spawnSync('astrale', ['start'], { stdio: 'inherit' })
  if (s.status !== 0) die('astrale start failed')
}

function ensureCloudflared(): void {
  console.log('==> cloudflared tunnel')
  const tunnelName = process.env.MINIMAL_TUNNEL_NAME ?? DEFAULT_TUNNEL_NAME
  const status = spawnSync('astrale', ['tunnel', 'status', tunnelName], {
    encoding: 'utf-8',
    stdio: ['inherit', 'pipe', 'inherit'],
  })
  if (status.status === 0 && /running/i.test(status.stdout)) {
    console.log(`    already running (${tunnelName})`)
    return
  }
  const r = spawnSync('astrale', ['tunnel', 'start', tunnelName], { stdio: 'inherit' })
  if (r.status !== 0) {
    die(
      `astrale tunnel start ${tunnelName} failed.\n` +
        `  If the tunnel isn't yet registered, run once:\n` +
        `    astrale tunnel setup ${tunnelName}\n` +
        `  (see skill reference deploy.md → "Cloudflare tunnel setup").`,
    )
  }
  console.log(`    started (${tunnelName})`)
}

async function ensureLocalWorker(): Promise<void> {
  console.log('==> wrangler dev')
  assertRuntimeSecrets()
  syncDevVars()
  const port = domain.port ?? readDomainPort()
  const localMeta = `http://localhost:${port}/meta`
  if (await isHttpOk(localMeta)) {
    console.log('    already running')
  } else {
    const logDir = process.env.MINIMAL_DEV_LOG_DIR ?? DEFAULT_DEV_LOG_DIR
    spawnSync('mkdir', ['-p', logDir])
    spawnSync('bash', [
      '-c',
      `cd ${domainRoot}/worker && nohup bunx wrangler dev --port ${port} > ${logDir}/wrangler.log 2>&1 &`,
    ])
    console.log(`    started; logs ${logDir}/wrangler.log`)
    await waitForUrl(localMeta, 30_000, 'wrangler')
  }

  if (workerIsTunneled) {
    await waitForUrl(`${workerUrl}/meta`, 60_000, 'tunnel → worker')
  }
}

function syncDevVars(): void {
  const devVars = join(domainRoot, 'worker', '.dev.vars')
  const url = domainUrl(domain)
  const body =
    '# Generated by scripts/infra-prepare.ts — do not hand-edit.\n' +
    `WORKER_URL=${url}\n` +
    `MINIMAL_BASE_DOMAIN=${domain.domain}\n`
  let prev = ''
  try {
    prev = readFileSync(devVars, 'utf-8')
  } catch {
    // file missing — treat as empty
  }
  if (prev === body) return
  writeFileSync(devVars, body)
  const port = domain.port ?? readDomainPort()
  const { killed } = killWranglerTree(port)
  if (killed > 0) console.log(`    .dev.vars changed — killed worker on :${port}`)
}

async function waitForUrl(url: string, timeoutMs: number, label: string): Promise<void> {
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    if (await isHttpOk(url)) {
      console.log(`    ${label} ready (${url})`)
      return
    }
    await new Promise((r) => setTimeout(r, 500))
  }
  die(`${label} did not become ready within ${Math.round(timeoutMs / 1000)}s (${url})`)
}

async function preflightDns(kn: KernelEnvName, dn: DomainEnvName): Promise<void> {
  const hostnames: { host: string; kind: 'tunnel' | 'local' }[] = []
  if (kernel.mode === 'standalone' && kn.endsWith(':tunneled')) {
    hostnames.push({ host: kernel.kernelDomain, kind: 'tunnel' })
  }
  if (kernel.mode === 'manager' && kn.endsWith(':tunneled') && kernel.instanceDomain) {
    hostnames.push({ host: kernel.instanceDomain.split('/')[0], kind: 'tunnel' })
  }
  if (dn === 'local:tunneled') {
    hostnames.push({ host: domain.domain, kind: 'tunnel' })
  } else if (dn === 'local:inprocess') {
    hostnames.push({ host: domain.domain, kind: 'local' })
  }
  const results = await Promise.all(
    hostnames.map((h) =>
      lookup(h.host).then(
        () => null,
        () => h,
      ),
    ),
  )
  const missing = results.filter((h): h is (typeof hostnames)[number] => h !== null)
  if (missing.length === 0) return

  console.error(`✗ DNS preflight failed for:`)
  for (const m of missing) console.error(`    - ${m.host} (${m.kind})`)
  const hasTunnel = missing.some((m) => m.kind === 'tunnel')
  const hasLocal = missing.some((m) => m.kind === 'local')
  if (hasTunnel) {
    console.error(
      `\nTunnel hostnames — run once per hostname:\n` +
        `  cloudflared tunnel route dns <tunnel-name> <hostname>\n` +
        `and add an ingress entry in ~/.cloudflared/config.yml.\n` +
        `See skill reference deploy.md → "Cloudflare tunnel setup".`,
    )
  }
  if (hasLocal) {
    const localHosts = missing.filter((m) => m.kind === 'local').map((m) => m.host)
    console.error(
      `\nLocal dev slugs — add to /etc/hosts:\n` +
        localHosts.map((h) => `  127.0.0.1 ${h}`).join('\n') +
        `\n(RFC 6761 resolvers handle \`.localhost\` automatically on most systems.)`,
    )
  }
  process.exit(1)
}

function parseArgs(argv: string[]): { kernel?: string; domain?: string } {
  const out: { kernel?: string; domain?: string } = {}
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--kernel') out.kernel = argv[++i]
    else if (argv[i] === '--domain') out.domain = argv[++i]
  }
  return out
}

function usage(): never {
  console.error(
    'Usage: infra-prepare.ts --kernel <kernel-preset> --domain <domain-preset>\n' +
      `  kernel: ${Object.keys(kernelEnvs).join(' | ')}\n` +
      `  domain: ${Object.keys(domainEnvs).join(' | ')}`,
  )
  process.exit(1)
}

function die(msg: string): never {
  console.error(`✗ ${msg}`)
  process.exit(1)
}
