// Generated by scripts/pin-agent-binaries.ts from pnpm-lock.yaml. Do not edit.
export const PINNED_AGENT_BINARIES = {
  claude: {
    label: 'Claude Code',
    version: '2.1.232',
    source: '@anthropic-ai/claude-agent-sdk@0.3.232',
    platforms: {
      'darwin-arm64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-arm64/-/claude-agent-sdk-darwin-arm64-0.3.232.tgz',
        integrity:
          'sha512-+/4PX+dwmQAjlOlooocwa3kClulZfMo133xQH3LYDlK7D5bzze16lwlDGPVAYGEarpvXg7G5JK8QjfWAJ2HYbg==',
        entry: 'package/claude',
      },
      'darwin-x64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-x64/-/claude-agent-sdk-darwin-x64-0.3.232.tgz',
        integrity:
          'sha512-EHZ1Y3aGyZ2mFZ6QLR1bM3/HiIn2cLrPjU+k3/oCIW6omJFodfzf410aWjDPSnMj7CE4d6t7MSjBWekMUbcv0g==',
        entry: 'package/claude',
      },
      'linux-arm64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64/-/claude-agent-sdk-linux-arm64-0.3.232.tgz',
        integrity:
          'sha512-wW2opwA5s7gLghjU6B2ADMAtoc7bAZMevUzi4g+1PXMJ8MGcPvbnx92EDYJrVDcZmAl1+fz19XyPsaShlisTzw==',
        entry: 'package/claude',
      },
      'linux-arm64-musl': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64-musl/-/claude-agent-sdk-linux-arm64-musl-0.3.232.tgz',
        integrity:
          'sha512-XkLcb9UT/l42Rtw7KBApzgxUe/kwoWJ9KCPcVEnYojzIvVR+AwBCl/QReNU5+6c72w48dYBMmLebI64gQbN0tg==',
        entry: 'package/claude',
      },
      'linux-x64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64/-/claude-agent-sdk-linux-x64-0.3.232.tgz',
        integrity:
          'sha512-6Px1xDiwQyLkSxwRQ34/kPA8WMXQ2rHYGkwockND7+9yMw+ShI3AfLkyi9G7JtJHObWFT6B82eSHjDS/Fy+9hQ==',
        entry: 'package/claude',
      },
      'linux-x64-musl': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64-musl/-/claude-agent-sdk-linux-x64-musl-0.3.232.tgz',
        integrity:
          'sha512-L1x2ge9NpXMLTczmT44TKPQ88PHE+gsCakQMVEOa8rXFvfBoqvcpxM0DT8wrqYWUHhQEYR8NXxQTP9a1NVRj8Q==',
        entry: 'package/claude',
      },
      'win32-arm64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-arm64/-/claude-agent-sdk-win32-arm64-0.3.232.tgz',
        integrity:
          'sha512-fDiuwL5dm1elOy7fNp4Qmdor8so4R8npj2pUGQA1G/xKfJhaK236aTWezvZid3L/O7cRdFeN9IVofOAlWLQcsw==',
        entry: 'package/claude.exe',
      },
      'win32-x64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-x64/-/claude-agent-sdk-win32-x64-0.3.232.tgz',
        integrity:
          'sha512-Hc/9uy1BI9mqKVyB1b/zoUnm3MFgtVNzQY6p5zgaq9DaIjCKDpR4a4L1aDZM4lMqUcWFMZM+u7juOhh+m39NBQ==',
        entry: 'package/claude.exe',
      },
    },
  },
  codex: {
    label: 'Codex',
    version: '0.148.0',
    source: '@openai/codex@0.148.0',
    platforms: {
      'darwin-arm64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.148.0-darwin-arm64.tgz',
        integrity:
          'sha512-xgBPFiF1fHUlRS7HE6wGB56LjBJh16kGD7b4TTbwdVBZNB4QDkTok+vdkAGrfpVkfKcwGNhPSKDgCw+KMZOVug==',
        entry: 'package/vendor/aarch64-apple-darwin/bin/codex',
      },
      'darwin-x64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.148.0-darwin-x64.tgz',
        integrity:
          'sha512-qepQolhJutfOp+e9i7L3xsi8aoWeCUiiRq274WMWqRj50rKTrXxsuAgkAwDbqEfT3G5VynhYZuQvDsW37JgdNQ==',
        entry: 'package/vendor/x86_64-apple-darwin/bin/codex',
      },
      'linux-arm64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.148.0-linux-arm64.tgz',
        integrity:
          'sha512-51DCd+izzk6n4mMh4w2utWj3lTLhSTnCOEJQfRh0LS9nBDkcYZcK3iSKOST6fByRIlLSXuLO33LlYYA1VPot6A==',
        entry: 'package/vendor/aarch64-unknown-linux-musl/bin/codex',
      },
      'linux-x64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.148.0-linux-x64.tgz',
        integrity:
          'sha512-uDT9s7AfMr9xLuJX3ZLVWHgHkUpCnZ33CZjZEdVQhrYCIErkDHsCW5TG290nNjaKngK0WxGt5uCcxeUHv9MWWA==',
        entry: 'package/vendor/x86_64-unknown-linux-musl/bin/codex',
      },
      'win32-arm64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.148.0-win32-arm64.tgz',
        integrity:
          'sha512-a8iOwLzs8UdnlWDHjgK3W/YSBBsUImG8X5XLBjengp3XGJRruhiIsQtUDUOYimCmotKPM4aX7Ub6zjl/KPxMQQ==',
        entry: 'package/vendor/aarch64-pc-windows-msvc/bin/codex.exe',
      },
      'win32-x64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.148.0-win32-x64.tgz',
        integrity:
          'sha512-/Jg8eYw0BqTGNUpnrzzWlK2kbu29NWg7t6pnUDEfxqpTUf+mK8r3okXQn60Zjbk9InYZ4d8SwSjrtOa+i5hSPw==',
        entry: 'package/vendor/x86_64-pc-windows-msvc/bin/codex.exe',
      },
    },
  },
} as const
