// Generated by scripts/pin-agent-binaries.ts from pnpm-lock.yaml. Do not edit.
export const PINNED_AGENT_BINARIES = {
  claude: {
    label: 'Claude Code',
    version: '2.1.286',
    source: '@anthropic-ai/claude-agent-sdk@0.3.286',
    platforms: {
      'darwin-arm64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-arm64/-/claude-agent-sdk-darwin-arm64-0.3.286.tgz',
        integrity:
          'sha512-gkxWcJ+Z23UxwghI1V3dL09PkELIZmB2vPelR8XsdfhS+yP1KvoW7FThvRLojcxXb3fj0ddYawjQSQYIkXFbxw==',
        entry: 'package/claude',
      },
      'darwin-x64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-x64/-/claude-agent-sdk-darwin-x64-0.3.286.tgz',
        integrity:
          'sha512-eMdni7sy1ud2IISI4QSsfVBCxotzSe62zCGdXISejL9MxDIwcRgEGZpO5OV+j7t8mNGMTe6Opl1t/3Z/1RUJaQ==',
        entry: 'package/claude',
      },
      'linux-arm64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64/-/claude-agent-sdk-linux-arm64-0.3.286.tgz',
        integrity:
          'sha512-3h+WWGek9beZ6i1qbIjjwYEFbs46D6qumjSBc6cLsEvnufcoi7mc0iBwbFSh9yRb3upxoi4ZTJdl53T3gLTdUQ==',
        entry: 'package/claude',
      },
      'linux-arm64-musl': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64-musl/-/claude-agent-sdk-linux-arm64-musl-0.3.286.tgz',
        integrity:
          'sha512-fG8Cqx53jkFyEL86ETA0tdLH3p06yFQKHcoxnMpiU+VmJ5g6uGFhsUZbJ6gFvuT3EgyMcNI2kZwhCCDF/DTnpQ==',
        entry: 'package/claude',
      },
      'linux-x64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64/-/claude-agent-sdk-linux-x64-0.3.286.tgz',
        integrity:
          'sha512-kNczbWhWJ1G8sPRZd4Nsx/Ozr/kx16lT2NGp/EEmTV4Hn732xfLkUOlg+tFcS78i6lOPBknjDB/cz/J5Ha4wDQ==',
        entry: 'package/claude',
      },
      'linux-x64-musl': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64-musl/-/claude-agent-sdk-linux-x64-musl-0.3.286.tgz',
        integrity:
          'sha512-WeO/wG2uPh95BhOQi1IsIECdW5gJgC1Q9xtGw4RjV04it1fBMAbUe7aVwP4DQgH8PHnmduA7dRnLtbnZnrGsjg==',
        entry: 'package/claude',
      },
      'win32-arm64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-arm64/-/claude-agent-sdk-win32-arm64-0.3.286.tgz',
        integrity:
          'sha512-N4p7Gw5Qg3q9+Y5sEht1cIHHZkmBAUfWXJnqfmDD7N8twqF3XNVK3w65hDLqli4i0ttuZu79bGmRGkgNGm9Imw==',
        entry: 'package/claude.exe',
      },
      'win32-x64': {
        tarball:
          'https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-x64/-/claude-agent-sdk-win32-x64-0.3.286.tgz',
        integrity:
          'sha512-pg35GRPBKyviod0i8Z3EVMzDnTiiiucuWUbyH1bVIFFN0UWCQQ+PRUJ15qrPKjL6+vlFxOX2ei9FfsWYjGYZwA==',
        entry: 'package/claude.exe',
      },
    },
  },
  codex: {
    label: 'Codex',
    version: '0.159.3',
    source: '@openai/codex@0.159.3',
    platforms: {
      'darwin-arm64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.159.3-darwin-arm64.tgz',
        integrity:
          'sha512-aI4UY14YURYxJxnRK+AE4QU+aek0mgtyyo7Rw9rNbCQUYETRQ0NYdJzU9ytljERGpPlht3dHHI1u4NhqHoDJDQ==',
        entry: 'package/vendor/aarch64-apple-darwin/bin/codex',
      },
      'darwin-x64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.159.3-darwin-x64.tgz',
        integrity:
          'sha512-KTOQOD184DMXpR3TqnDUnLsgad14WJn+x3XmjBaXRHchKYGttjREwqrwzC61xQYFeh6VkogAceybR+SMbbgvYQ==',
        entry: 'package/vendor/x86_64-apple-darwin/bin/codex',
      },
      'linux-arm64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.159.3-linux-arm64.tgz',
        integrity:
          'sha512-84C1yhAI+i0hqh77Akp/Ma09Z4d5oLKcZKqW1WZpEDh8bKbNvvbNEd6pE+GMUe2Kwg7jCbuvkRNH1zgK+SCM3Q==',
        entry: 'package/vendor/aarch64-unknown-linux-musl/bin/codex',
      },
      'linux-x64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.159.3-linux-x64.tgz',
        integrity:
          'sha512-xlHydfOksnNt/qz4BEVFvjMWunweaVSNtha/DkVUwWZnVZxbqiJwsXSl2iZDk04b6k/g0OI7jU06XqzHB2s5og==',
        entry: 'package/vendor/x86_64-unknown-linux-musl/bin/codex',
      },
      'win32-arm64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.159.3-win32-arm64.tgz',
        integrity:
          'sha512-4C+EuH1zE4rO5w1MsrnS98Tvq6Ff4+zeNr3pVeR/UsQ+VrTY5BCA9nZuXuCXNLKak1tLOw81b+fQM4jKGFCeDA==',
        entry: 'package/vendor/aarch64-pc-windows-msvc/bin/codex.exe',
      },
      'win32-x64': {
        tarball: 'https://registry.npmjs.org/@openai/codex/-/codex-0.159.3-win32-x64.tgz',
        integrity:
          'sha512-h8w5nslfQyoYbonZaRlLwvPKFS9Mcxz5vUeCeoHKF5SsZUP9jSBH7hxUdc8RWJffJtfbV2qxdnImVAj9zy2fwA==',
        entry: 'package/vendor/x86_64-pc-windows-msvc/bin/codex.exe',
      },
    },
  },
} as const
