/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KernelIdRouteImport } from './routes/kernel/$id'
import { Route as KernelRemoteSlugRouteImport } from './routes/kernel/remote/$slug'
import { Route as PlaygroundRouteImport } from './routes/playground'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KernelIdRoute = KernelIdRouteImport.update({
  id: '/kernel/$id',
  path: '/kernel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KernelRemoteSlugRoute = KernelRemoteSlugRouteImport.update({
  id: '/kernel/remote/$slug',
  path: '/kernel/remote/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/kernel/$id': typeof KernelIdRoute
  '/kernel/remote/$slug': typeof KernelRemoteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/kernel/$id': typeof KernelIdRoute
  '/kernel/remote/$slug': typeof KernelRemoteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/kernel/$id': typeof KernelIdRoute
  '/kernel/remote/$slug': typeof KernelRemoteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/playground' | '/kernel/$id' | '/kernel/remote/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playground' | '/kernel/$id' | '/kernel/remote/$slug'
  id: '__root__' | '/' | '/playground' | '/kernel/$id' | '/kernel/remote/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  KernelIdRoute: typeof KernelIdRoute
  KernelRemoteSlugRoute: typeof KernelRemoteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kernel/$id': {
      id: '/kernel/$id'
      path: '/kernel/$id'
      fullPath: '/kernel/$id'
      preLoaderRoute: typeof KernelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kernel/remote/$slug': {
      id: '/kernel/remote/$slug'
      path: '/kernel/remote/$slug'
      fullPath: '/kernel/remote/$slug'
      preLoaderRoute: typeof KernelRemoteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  KernelIdRoute: KernelIdRoute,
  KernelRemoteSlugRoute: KernelRemoteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
