#!/usr/bin/env bun
import { createHash, randomUUID } from 'node:crypto'
import { lstat, mkdir, readFile, readdir, readlink, rename, rm, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gzipSync } from 'node:zlib'

type PackedFile = {
  path: string
  mode: number
  contents: string
}

type PackedArchive = {
  format: 1
  version: string
  files: PackedFile[]
}

type EmbeddedSkill = {
  name: string
  path: string
  tree: string
}

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const OUTPUT = join(ROOT, 'src', 'generated', 'embedded-assets.ts')
const ARCHIVE_VERSION = '1'

function gitObjectHash(type: 'blob' | 'tree', body: Buffer): Buffer {
  return createHash('sha1')
    .update(Buffer.from(`${type} ${body.length}\0`))
    .update(body)
    .digest()
}

async function gitTreeHash(directory: string): Promise<string> {
  async function hashTree(current: string): Promise<Buffer> {
    const entries = await Promise.all(
      (await readdir(current)).map(async (name) => {
        const path = join(current, name)
        const stat = await lstat(path)
        if (stat.isDirectory()) {
          return { name, sort: `${name}/`, mode: '40000', hash: await hashTree(path) }
        }
        if (stat.isSymbolicLink()) {
          return {
            name,
            sort: name,
            mode: '120000',
            hash: gitObjectHash('blob', Buffer.from(await readlink(path))),
          }
        }
        return {
          name,
          sort: name,
          mode: stat.mode & 0o111 ? '100755' : '100644',
          hash: gitObjectHash('blob', await readFile(path)),
        }
      }),
    )
    entries.sort((a, b) => Buffer.compare(Buffer.from(a.sort), Buffer.from(b.sort)))
    return gitObjectHash(
      'tree',
      Buffer.concat(
        entries.flatMap((entry) => [Buffer.from(`${entry.mode} ${entry.name}\0`), entry.hash]),
      ),
    )
  }
  return (await hashTree(directory)).toString('hex')
}

async function collectFiles(root: string, prefix: string): Promise<PackedFile[]> {
  const files: PackedFile[] = []
  async function visit(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const absolute = join(directory, entry.name)
      if (entry.isDirectory()) {
        await visit(absolute)
        continue
      }
      if (!entry.isFile()) throw new Error(`embedded asset must be a regular file: ${absolute}`)
      const stat = await lstat(absolute)
      files.push({
        path: `${prefix}/${relative(root, absolute).split('\\').join('/')}`,
        mode: stat.mode & 0o111 ? 0o755 : 0o644,
        contents: (await readFile(absolute)).toString('base64'),
      })
    }
  }
  await visit(root)
  return files.sort((a, b) => Buffer.compare(Buffer.from(a.path), Buffer.from(b.path)))
}

const skillNames = (await readdir(join(ROOT, 'skills'), { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort()
const skills: EmbeddedSkill[] = []
const skillFiles: PackedFile[] = []
for (const name of skillNames) {
  const directory = join(ROOT, 'skills', name)
  const names = await readdir(directory)
  if (!names.includes('SKILL.md')) continue
  skills.push({
    name,
    path: `skills/${name}/SKILL.md`,
    tree: await gitTreeHash(directory),
  })
  skillFiles.push(...(await collectFiles(directory, `skills/${name}`)))
}
if (skills.length === 0) throw new Error('no Astrale skills found')

const archive: PackedArchive = {
  format: 1,
  version: ARCHIVE_VERSION,
  files: [
    ...skillFiles,
    ...(await collectFiles(join(ROOT, 'studio', 'client', 'dist'), 'studio')),
    ...(await collectFiles(join(ROOT, 'viewer', 'dist'), 'viewer')),
  ],
}
const compressed = gzipSync(Buffer.from(JSON.stringify(archive)), { level: 9 })
if (compressed[0] !== 0x1f || compressed[1] !== 0x8b || compressed.length < 10) {
  throw new Error('embedded asset compressor did not emit a gzip stream')
}
// RFC 1952 byte 9 identifies the compressor's operating system but does not affect
// decompression. Bun emits a platform-specific value, so normalize it before hashing.
compressed[9] = 0xff
const digest = createHash('sha256').update(compressed).digest('hex')
const chunks = compressed
  .toString('base64')
  .match(/.{1,100}/gu)
  ?.map((chunk) => `  '${chunk}',`)
  .join('\n')
if (!chunks) throw new Error('embedded asset archive is empty')

const unformatted =
  `// Generated by scripts/generate-embedded-assets.ts. Do not edit.\n` +
  `export const EMBEDDED_ASSET_FORMAT = 1 as const\n` +
  `export const EMBEDDED_ASSET_VERSION = ${JSON.stringify(ARCHIVE_VERSION)}\n` +
  `export const EMBEDDED_ASSET_DIGEST = ${JSON.stringify(digest)}\n` +
  `export const EMBEDDED_SKILLS = ${JSON.stringify(skills, null, 2)} as const\n` +
  `export const EMBEDDED_ASSET_ARCHIVE_BASE64 = [\n${chunks}\n].join('')\n`
const formatter = join(ROOT, 'node_modules', '.bin', 'oxfmt')
await mkdir(dirname(OUTPUT), { recursive: true })
const temporary = `${OUTPUT}.${process.pid}.${randomUUID()}.ts`
try {
  await writeFile(temporary, unformatted)
  const formatted = Bun.spawnSync([formatter, '--write', temporary], {
    stdout: 'ignore',
    stderr: 'pipe',
  })
  if (formatted.exitCode !== 0) {
    throw new Error(`could not format embedded assets: ${formatted.stderr.toString().trim()}`)
  }

  const source = await readFile(temporary, 'utf8')
  if (process.argv.includes('--check')) {
    const current = await readFile(OUTPUT, 'utf8').catch(() => '')
    if (current !== source) {
      console.error('embedded assets are stale — run: bun scripts/build-embedded-assets.ts')
      process.exitCode = 1
    }
  } else {
    await rename(temporary, OUTPUT)
    console.log(
      `embedded ${archive.files.length} files (${compressed.length} compressed bytes, ${skills.length} skills)`,
    )
  }
} finally {
  await rm(temporary, { force: true }).catch(() => undefined)
}
